CREATE TABLE myNewDB.USERS
(
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USERID INTEGER NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    City VARCHAR(255) NOT NULL
);
